# Variable
@url = localhost:3000

### Get all books
GET {{url}}/books

### Create book
POST {{url}}/books
Content-Type: application/json

{
  "name": "test",
  "author": "test"
}

### Get book by ID
GET {{url}}/books/1757513011744

### Update book by ID
PUT {{url}}/books/1757513011744

{
  "name": "testing",
  "author": "testing"
}

### Get all products
GET {{url}}/products

### Create product
POST {{url}}/products
Content-Type: application/json

{
  "name": "test",
  "deskripsi": "test",
  "price": 123
}

### Get product by ID
GET {{url}}/products/1757512651969

### Update product by ID
PUT {{url}}/products/1757512651969

{
  "name": "testing",
  "deskripsi": "testing",
  "price": 1234
}
